### PR TITLE
Correcting specified package type in error message

### PR DESCRIPTION
**Pull request by danielhoherd**
Simple human language typo correction.

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=58) <br/>All committers have signed the CLA.

**Review by svetasmirnova — APPROVED** [review]
Thank you for your contribution.

Could you please sign CLA?

**Comment by danielhoherd** [comment]
LOL, I was like "why don't I remember this PR? Oh. It's 7 years old."

**Review by BupycHuk — APPROVED** [review]

**Comment by danielhoherd** [comment]
I don't see anything left for me to do, but the clahub check is still failing even though I signed the CLA check linked in the comment above. Please link me anything else I need to sign.

**Pull request merged**
