### PR TITLE
pt-osc: Fails with duplicate key in table for self-referencing FK

### PR DESCRIPTION
**Pull request by amiel-marqeta**
pt-online-schema-change fails with duplicate key in table for self-referencing FK
https://bugs.launchpad.net/percona-toolkit/+bug/1632522

### CODE REVIEW

**Comment by percona-csalguero** [comment]
Could you add a test case?

**Comment by amiel-marqeta** [comment]
Stupid question... Can you please point me to some doc on how to setup the test environment so I can run the new test I'm creating?

**Comment by percona-csalguero** [comment]
Oh, yes, sorry. Tomorrow I am going to add a document to the repo explaining how to set up the environment.
Thanks for you help and patience.

**Comment by amiel-marqeta** [comment]
Cool, looking forward to setting up the test env. Also from the docs 
> DROP FOREIGN KEY constraint_name requires specifying _constraint_name rather than the real
What if the tool looks up the _real_ constraint name from the new table? This would be ideal as it will be transparent to the users.

**Comment by percona-csalguero** [comment]
Hi.
I've added explanations here: https://github.com/percona/percona-toolkit/blob/2.2/CONTRIBUTE.md#setting-up-the-development-environment
Please let me know if you need something else.
Regards

**Comment by amiel-marqeta** [comment]
OK, added the tests and made adjustment to existing rename_fk test.

**Comment by percona-csalguero** [comment]
I ran the tests and everything looks good.
I need one more thing: could you add a comment saying the code provided is your own creation and it can be distributed under BSD licence, please?

**Comment by amiel-marqeta** [comment]
I actually made one more change to compatibility with older Perl versions.

This is my own creation and it can be distributed under BSD license.

**Comment by percona-csalguero** [comment]
Thanks @amiel-marqeta

**Pull request merged**
