### PR TITLE
Fix MariaDB 10.3 compatibility

### PR DESCRIPTION
**Pull request by SMillerDev**
This implements the patch provided in https://jira.percona.com/browse/PT-1518

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=406) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=406) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=406) it.</sub>

**Comment by Rohlik** [comment]
We are waiting for this. Looking forward.

**Comment by SMillerDev** [comment]
@percona-csalguero got time to review this?

**Comment by percona-csalguero** [comment]
Hello, 

The fixes work but they belong into the `RowChecksum.pm` and `TableSyncNibble.pm` modules and all the programs using those modules should be updated.

**Comment by percona-csalguero** [comment]
I checked and there are no other programs using those libs, but we need to update the libs anyway to keep the code consistent.
Could you please add the changes in `lib/RowChecksum.pm` and `lib/TableSyncer.pm` please?

Thanks.

**Comment by SMillerDev** [comment]
I'll try but I mostly just copied the patch to a PR.

**Comment by percona-csalguero** [comment]
Hello.

It is basically, modifying those lines into the modules.
I can do it for you but I always prefer to respect the author of the original PR instead of creating a new patch where I am the author.

Regards

**Comment by SMillerDev** [comment]
> I can do it for you but I always prefer to respect the author of the original PR instead of creating a new patch where I am the author.

Please do, I'm just a user of the tools and I don't really know what the patch does. I just know it works after and it wasn't being seen in jira.

**Comment by SMillerDev** [comment]
@percona-csalguero did you ever make your own PR?

**Comment by ovidiustanila** [comment]
Created a new pull request with required changes to lib/RowChecksum.pm and lib/TableSyncer.pm as requested by @percona-csalguero . Works fine on our servers with MariaDB 10.3.17 
#415

**Pull request closed without merging**
