### PR TITLE
replaced have_innodb for innodb_buffer_pool_size because the former i…

### PR DESCRIPTION
**Pull request by fipar**
…s no longer present on 5.7

### CODE REVIEW

**Review by svetasmirnova — APPROVED** [review]

**Comment by percona-csalguero** [comment]
LGTM, we just need to fix the conflicts

**Review by percona-csalguero — CHANGES_REQUESTED** [review]
LGTM. Could you fix the merge conflicts?
Thanks

**Comment by svetasmirnova** [comment]
Actually looks like this issue is already fixed in the 3.x branch by using operator || and variable innodb_version:

```   section "InnoDB"
   local have_innodb="$(get_var "have_innodb" "$dir/mysql-variables")"
   local innodb_version="$(get_var "innodb_version" "$dir/mysql-variables")"
   if [ "${have_innodb}" = "YES" ] || [ -n "${innodb_version}" ]; then 
...
```

**Comment by svetasmirnova** [comment]
Closed, because this issue is already resolved.

**Pull request closed without merging**
