### PR TITLE
remove depedency on github.com/prometheus/common/log

### PR DESCRIPTION
**Pull request by rlankfo**
This removes the dependency on github.com/prometheus/common/log which has been removed, allowing upgrade to newer versions of this package.

For now, I've replaced this with the log package from the standard library for simplicity sake.

### CODE REVIEW

**Comment by bboreham** [comment]
Do the `go.sum` diffs get smaller if you run `go mod tidy` ?

**Comment by rlankfo** [comment]
> Do the `go.sum` diffs get smaller if you run `go mod tidy` ?

Yes, thanks for pointing this out 👍

**Review by percona-csalguero — APPROVED** [review]

**Comment by rlankfo** [comment]
@denisok @percona-csalguero Any chance of getting this merged soon?

**Comment by percona-csalguero** [comment]
@rlankfo Merged.

**Pull request merged**
