### PR TITLE
Add CPU cache configuration info to pt-summary.

### PR DESCRIPTION
**Pull request by akopytov**

### CODE REVIEW

**Comment by akopytov** [comment]
Is anybody looking at external pull requests for PT? Should I use another channel to submit this contribution? Thanks.

**Comment by percona-csalguero** [comment]
Could you add a comment saying that the code is your own creation and it can be distributed under the BSD licence? 

Please check: https://github.com/percona/percona-toolkit/blob/2.2/CONTRIBUTE.md

**Comment by akopytov** [comment]
The code is my creation and can be distributed under the BSD license.

**Comment by percona-csalguero** [comment]
I am getting this:
```
          Designation               Configuration            Size        Associativity
  ========================= ============================== ======== ======================
```
What's the idea about this PR? What it should do? Could you provide an example?

**Comment by akopytov** [comment]
It uses data about the CPU cache provided by the dmidecode utility (https://linux.die.net/man/8/dmidecode). pt-summary already uses dmidecode (if avaliable) to provide information about available memory devices. The patch piggybacks on that functionality to describe CPU cache, e.g. available caches, their sizes and associativity.

**Comment by akopytov** [comment]
I think I tested it on an Intel Xeon machine and worked fine. As I understand, you got empty output. Can you give me the output of `dmidecode -t cache` on your machine?

**Comment by akopytov** [comment]
Is there anything I can do to get this PR merged?

**Comment by percona-csalguero** [comment]
Sorry for the delay.
I need to review the changes and if everything is OK, I am going to merge it.
Thanks for your help

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=140) <br/>All committers have signed the CLA.

**Review by svetasmirnova — CHANGES_REQUESTED** [review]
Thank you for your contribution.

You modified the auto-generated code. It will be removed once we run the update-modules utility. Please put your changes into the report_system_info package. Please also add a test case. You will find examples in the directory t.

**Review by svetasmirnova — APPROVED** [review]

**Review by EvgeniyPatlan — APPROVED** [review]

**Review by saikumar-vs — APPROVED** [review]

**Pull request merged**
