### PR TITLE
War on typos Act 4

### PR DESCRIPTION
**Pull request by szepeviktor**
- [x] The contributed code is licensed under GPL v2.0
- [x] Contributor Licence Agreement (CLA) is signed
- [ ] util/update-modules has been ran
- [ ] Documention updated
- [ ] Test suite update

Convert Windows line ends to LF. Some contributors have Windows editors.

No content change! Review without whitespace changes: https://github.com/percona/percona-toolkit/pull/660/files?diff=unified&w=1

### CODE REVIEW

**Comment by szepeviktor** [comment]
@svetasmirnova Would you welcome a PR adding [CI workflows to prevent these problems](https://github.com/szepeviktor/byte-level-care/tree/master/.github/workflows#list-of-all-jobs) once and for all?

**Comment by svetasmirnova** [comment]
> @svetasmirnova Would you welcome a PR adding [CI workflows to prevent these problems](https://github.com/szepeviktor/byte-level-care/tree/master/.github/workflows#list-of-all-jobs) once and for all?

Yes, it would be nice.

Regarding the current PR - I need to check if we can change the line endings for NaturalDocs.

**Comment by szepeviktor** [comment]
> I need to check if we can change the line endings for NaturalDocs.

I've just downloaded [`NaturalDocs-1.52.zip`](https://sourceforge.net/projects/naturaldocs/files/Stable%20Releases/1.52/NaturalDocs-1.52.zip/download). Its content is ISO-8859-1 (latin1) encoded.
Those "?" characters are ISO-8859-1 `©` characters but in UTF-8 they are invalid.

I prepare a PR that adds **the original** content from the ZIP recoded into UTF-8 + LF line ends.

**Comment by svetasmirnova** [comment]
@alina-derkach-oaza Please check NaturalDocs changes. Do we use this package for docs now? Will this line-ending change affect anything?

**Comment by szepeviktor** [comment]
@alina-derkach-oaza This PR is superseded by #662

**Pull request closed without merging**
