### PR TITLE
Fix --check-slave-lag (PT-178)

### PR DESCRIPTION
**Pull request by dveeden**
https://jira.percona.com/browse/PT-178

### CODE REVIEW

**Comment by dveeden** [comment]
Related to https://github.com/percona/percona-toolkit/pull/119

**Comment by bartoszcisek** [comment]
Hey! This PR sound would be super useful, what stops you from merging? :-)

**Comment by dveeden** [comment]
I also would like to get this merged. I don't remember if there were any outstanding issues with this PR. Until this is fixed I'll use the last version that still has this functionality

**Comment by percona-csalguero** [comment]
Hi, 

Thanks for submitting this fix.
I ran the tests and it breaks t/pt-online-schema-change/slave_lag.t.
Could you please check it?

Thanks

**Review by percona-csalguero — CHANGES_REQUESTED** [review]
Thanks for submitting this fix.
I ran the tests and it breaks t/pt-online-schema-change/slave_lag.t.
Could you please check it?

Thanks

**Comment by dveeden** [comment]
By now there are quite a few non-trivial conflicts. I also currently don't have good of (re)testing these changes.

**Pull request closed without merging**
