### PR TITLE
PT-1518 pt-table-checksum gives error CRC32

### PR DESCRIPTION
**Pull request by ovidiustanila**
Fixes #PT-1518
Extended fix for #406

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=415) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=415) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=415) it.</sub>

**Comment by Rohlik** [comment]
Can be this merged @percona-csalguero ? We are waiting for this fix.

**Comment by Rohlik** [comment]
Why is there no effort from Percona to merge this to master?

**Comment by Rohlik** [comment]
@percona-csalguero Thank you so much for this!

**Comment by rnovikovP** [comment]
Thanks to  @ovidiustanila and @SMillerDev for this fix!

**Pull request merged**
