### PR TITLE
Recheck the list of slaves in the table specified with DSN

### PR DESCRIPTION
**Pull request by dveeden**
This is to add/remove monitored machines while the OSC runs.

This contains work by:
- Daniël van Eeden <daniel.vaneeden@booking.com>
- Mikhail Izioumtchenko <mikhail.izioumtchenko@booking.com>

### CODE REVIEW

**Comment by percona-csalguero** [comment]
All tests successful.
Files=18, Tests=284, 162 wallclock secs ( 0.10 usr  0.00 sys +  6.88 cusr  1.26 csys =  8.24 CPU)
Result: PASS

**Comment by percona-csalguero** [comment]
Hi @dveeden 
Could you add a comment stating that the submitted code is your own creation and it can be distributed under the terms of the BSD licence please?

**Comment by dveeden** [comment]
Yes the BSD license is fine. Thanks

**Comment by cfsalguero** [comment]
I had to revert this.
It produces a regression in `--check-slave-lag` & `--skip-check-slave-lag`

**Comment by percona-csalguero** [comment]
I've added [this test file](https://github.com/percona/percona-toolkit/blob/3.0/t/pt-online-schema-change/slave_lag.t) to make it easier to test.  
Sorry I didn't have enough time to work a fix myself.
There are 2 things to change:  

1. The `$pr_refresh_slave_list` sub should include a filter for the `--skip-check-slave-lag` option
2. IIRC, `$get_slaves_cb` at line [8447](https://github.com/percona/percona-toolkit/pull/119/files#diff-434219c6b6b38d2b6ab91c0f6da5cd83R8447) should return something like: 
```
 $get_slaves_cb = sub {
    return [ $cxn ];
}
```

**Pull request merged**
