### PR TITLE
point is not decimal

### PR DESCRIPTION
**Pull request by frantzcy**
prevent field type 'point' to  be taken as decimal   (poINT)

### CODE REVIEW

**Comment by percona-csalguero** [comment]
Hi, 

Thanks for you help with this fix.
Before being able to merge it, we need to write a test case and we need a comment from you saying the code is your own creation and it can be distributed under the BSD license. 

In the file [CONTRIBUTE.md](https://github.com/percona/percona-toolkit/blob/2.2/CONTRIBUTE.md) you can find more information about the process and some other useful information like how to set up the testing env.

Please let me know if I can be any help.

**Comment by frantzcy** [comment]
The \b I added into the is all my creation and can be distributed under the BSD license.

**Comment by percona-csalguero** [comment]
:+1: :smile:

**Comment by percona-csalguero** [comment]
@frantzcy could you sing the contributor agreement please?

**Comment by frantzcy** [comment]
I will get this 'signed'.

**Comment by frantzcy** [comment]
signed !

**Comment by percona-csalguero** [comment]
I still getting: 
clahub — Not all contributors have signed the Contributor License Agreement.

**Comment by frantzcy** [comment]
Interesting !

So.. this is not enough https://www.clahub.com/agreements/frantzcy/percona-toolkit 

And this does not exist:  https://www.clahub.com/agreements/percona/percona-toolkit

Anything you can do to help me with this?

**Comment by frantzcy** [comment]
Any clue ?

**Comment by percona-csalguero** [comment]
Let me check and I'll let you know when it is fixed

**Pull request merged**
